Only build msentraid and himmelblau packages when building authd-msentraid
Fixes this build failure of authd-google:

    :: internal/providers/msentraid/himmelblau/himmelblau_c.go:10:10: fatal error: himmelblau.h: No such file or directory
    ::    10 | #include "himmelblau.h"

We have to move the errors into a separate file which is also built
without the tag because internal/broker/broker.go uses those.

Also, make golangci-lint use the withmsentraid build tag so that the
msentraid and himmelblau packages are also linted by it.

We should be able to revert this if/when we refactor the broker so that
the broker-specific code depends on the generic code instead of the
other way around.